when:
  event: tag

pipeline:
  tag:
    image: docker:git
    secrets:
      - GIT_EMAIL
      - GIT_USERNAME
    commands:
      - git config --global user.email "${GIT_EMAIL}"
      - git config --global user.name "${GIT_USERNAME}"
      - git tag latest
      - git push origin latest

  build:
    image: node:18.12
    commands:
      - yarn install --frozen-lockfile
      - yarn build:all

  zip:
    image: lunagod/drone-zip
    settings:
      input:
        - dist
      output: timeline-latest.zip

  release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url:
        from_secret: gitea_host
      title: Master Release
      draft: false
      prerelease: true
      files:
        - timeline-latest.zip
