name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
      - name: Tag
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run:  yarn install --frozen-lockfile

      - name: Build
        run:  yarn build:all

      - name: Zip
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: timeline-${{ SHA8 }}.zip
          path: dist

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: timeline-${{ SHA8 }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: Master Release
          draft: false
          prerelease: true
          tag: latest

