name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn install --frozen-lockfile
        run: yarn build:all
      - name: Zip
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: timeline-${SHA8}.zip
          path: dist
      - name: Release
        uses: actions/create-release@v1
        with:
          artifacts: timeline-${SHA8}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: Master Release
          draft: false
          prerelease: true

